image: docker.io/texlive/texlive

stages:
  - build

compile_main.pdf:
  stage: build
  script:
    - latexmk -pdflua
  artifacts:
    paths:
      - main.pdf
    expire_in: 1 week
  interruptible: true
