image: core.harbor.ricerca.sesar.di.unimi.it/docker/texlive/texlive

stages:
  - build

compile_main.pdf:
  stage: build
  script:
    - latexmk -pdflua main.tex
  artifacts:
    paths:
      - main.pdf
    expire_in: 1 week
  interruptible: true
