image: docker.io/nixpkgs/nix-flakes

stages:
  - build

build:
  stage: build
  script:
    - nix build -v
    - cp result main.pdf
  artifacts:
    name: "Document"
    expose_as: "Document"
    expire_in: "1 mos"
    paths:
      - ./main.pdf
